# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pjmini.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(528, 471)
        Dialog.setMinimumSize(QtCore.QSize(520, 471))
        Dialog.setMaximumSize(QtCore.QSize(528, 16777215))
        Dialog.setStyleSheet("background-image: url(:/cat/photo/56ea04557da1b2cad74b5d3fcc08c3ff.jpg);")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(160, 40, 371, 301))
        self.listView.setStyleSheet("background-image: url(:/cat/photo/แมวส้ม-1.jpg);")
        self.listView.setObjectName("listView")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 0, 119, 23))
        self.pushButton_5.setStyleSheet("background-image: url(:/newPrefix/python/bbceen.jpg);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 119, 23))
        self.pushButton_4.setStyleSheet("background-image: url(:/newPrefix/python/bbceen.jpg);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 70, 229, 31))
        self.pushButton_6.setStyleSheet("background-image: url(:/newPrefix/python/bbceen.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(300, 110, 229, 31))
        self.pushButton_7.setStyleSheet("background-image: url(:/newPrefix/python/bbceen.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 0, 119, 23))
        self.pushButton_9.setStyleSheet("background-image: url(:/newPrefix/python/bbceen.jpg);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(300, 230, 229, 31))
        self.pushButton_10.setStyleSheet("background-image: url(:/newPrefix/python/bbceen.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(300, 270, 229, 31))
        self.pushButton_14.setStyleSheet("background-image: url(:/newPrefix/python/bbceen.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.listView_4 = QtWidgets.QListView(Dialog)
        self.listView_4.setGeometry(QtCore.QRect(0, 40, 271, 301))
        self.listView_4.setStyleSheet("background-image: url(:/cafe/crop/1.jpg);")
        self.listView_4.setObjectName("listView_4")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(0, 350, 291, 121))
        self.plainTextEdit_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-image: url(:/cat/photo/ปุ่ม1.jpg);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(300, 190, 229, 31))
        self.pushButton_13.setStyleSheet("background-image: url(:/newPrefix/python/bbceen.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.listView_5 = QtWidgets.QListView(Dialog)
        self.listView_5.setGeometry(QtCore.QRect(0, 60, 271, 261))
        self.listView_5.setStyleSheet("background-image: url(:/cafe/crop/2.jpg);")
        self.listView_5.setObjectName("listView_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(0, 350, 291, 121))
        self.plainTextEdit_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-image: url(:/cat/photo/ปุ่ม1.jpg);")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.listView_6 = QtWidgets.QListView(Dialog)
        self.listView_6.setGeometry(QtCore.QRect(0, 60, 271, 261))
        self.listView_6.setStyleSheet("background-image: url(:/cafe/crop/3.3.jpg);")
        self.listView_6.setObjectName("listView_6")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(0, 350, 291, 121))
        self.plainTextEdit_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-image: url(:/cat/photo/ปุ่ม1.jpg);")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(0, 60, 281, 391))
        self.plainTextEdit_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-image: url(:/cat/photo/ปุ่ม1.jpg);")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(0, 60, 531, 301))
        self.listWidget.setStyleSheet("background-image: url(:/cat/photo/5.jpg);")
        self.listWidget.setObjectName("listWidget")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(150, 380, 256, 71))
        self.textBrowser.setStyleSheet("background-image: url(:/cat/photo/ปุ่ม2.jpg);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(270, 360, 256, 71))
        self.textBrowser_2.setStyleSheet("background-image: url(:/cat/photo/ปุ่ม2.jpg);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.listView.raise_()
        self.plainTextEdit_3.raise_()
        self.plainTextEdit_4.raise_()
        self.plainTextEdit_5.raise_()
        self.plainTextEdit_6.raise_()
        self.listWidget.raise_()
        self.pushButton_5.raise_()
        self.pushButton_4.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_14.raise_()
        self.pushButton_13.raise_()
        self.listView_5.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.listView_6.raise_()
        self.listView_4.raise_()

        self.retranslateUi(Dialog)
        self.pushButton_4.clicked.connect(self.listView.show) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_5.show) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_9.show) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_6.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_7.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_6.show) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_7.show) # type: ignore
        self.pushButton_5.clicked.connect(self.listView.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_4.show) # type: ignore
        self.pushButton_5.clicked.connect(Dialog.show) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_7.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_10.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_14.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_10.show) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_14.show) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_10.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_14.close) # type: ignore
        self.pushButton_4.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton_9.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton_5.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton_7.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton_13.clicked.connect(self.listView_4.show) # type: ignore
        self.pushButton_13.clicked.connect(self.plainTextEdit_3.show) # type: ignore
        self.pushButton_4.clicked.connect(self.listView_4.close) # type: ignore
        self.pushButton_9.clicked.connect(self.listView_4.close) # type: ignore
        self.pushButton_5.clicked.connect(self.listView_4.close) # type: ignore
        self.pushButton_6.clicked.connect(self.listView_4.close) # type: ignore
        self.pushButton_7.clicked.connect(self.listView_4.close) # type: ignore
        self.pushButton_10.clicked.connect(self.listView_4.close) # type: ignore
        self.pushButton_14.clicked.connect(self.listView_4.close) # type: ignore
        self.pushButton_4.clicked.connect(self.plainTextEdit_3.close) # type: ignore
        self.pushButton_9.clicked.connect(self.plainTextEdit_3.close) # type: ignore
        self.pushButton_5.clicked.connect(self.plainTextEdit_3.close) # type: ignore
        self.pushButton_6.clicked.connect(self.plainTextEdit_3.close) # type: ignore
        self.pushButton_7.clicked.connect(self.plainTextEdit_3.close) # type: ignore
        self.pushButton_10.clicked.connect(self.plainTextEdit_3.close) # type: ignore
        self.pushButton_14.clicked.connect(self.plainTextEdit_3.close) # type: ignore
        self.pushButton_13.clicked.connect(self.listView_4.show) # type: ignore
        self.pushButton_13.clicked.connect(self.plainTextEdit_3.show) # type: ignore
        self.pushButton_13.clicked.connect(self.listView_4.show) # type: ignore
        self.pushButton_6.clicked.connect(self.pushButton_13.show) # type: ignore
        self.pushButton_4.clicked.connect(self.listView_5.close) # type: ignore
        self.pushButton_9.clicked.connect(self.listView_5.close) # type: ignore
        self.pushButton_5.clicked.connect(self.listView_5.close) # type: ignore
        self.pushButton_6.clicked.connect(self.listView_5.close) # type: ignore
        self.pushButton_7.clicked.connect(self.listView_5.close) # type: ignore
        self.pushButton_13.clicked.connect(self.listView_5.close) # type: ignore
        self.pushButton_14.clicked.connect(self.listView_5.close) # type: ignore
        self.pushButton_4.clicked.connect(self.plainTextEdit_4.close) # type: ignore
        self.pushButton_9.clicked.connect(self.plainTextEdit_4.close) # type: ignore
        self.pushButton_5.clicked.connect(self.plainTextEdit_4.close) # type: ignore
        self.pushButton_6.clicked.connect(self.plainTextEdit_4.close) # type: ignore
        self.pushButton_7.clicked.connect(self.plainTextEdit_4.close) # type: ignore
        self.pushButton_13.clicked.connect(self.plainTextEdit_4.close) # type: ignore
        self.pushButton_14.clicked.connect(self.plainTextEdit_4.close) # type: ignore
        self.pushButton_10.clicked.connect(self.listView_5.show) # type: ignore
        self.pushButton_10.clicked['bool'].connect(self.plainTextEdit_4.show) # type: ignore
        self.pushButton_4.clicked.connect(self.listView_6.close) # type: ignore
        self.pushButton_9.clicked.connect(self.listView_6.close) # type: ignore
        self.pushButton_5.clicked.connect(self.listView_6.close) # type: ignore
        self.pushButton_6.clicked.connect(self.listView_6.close) # type: ignore
        self.pushButton_7.clicked.connect(self.listView_6.close) # type: ignore
        self.pushButton_13.clicked.connect(self.listView_6.close) # type: ignore
        self.pushButton_10.clicked.connect(self.listView_6.close) # type: ignore
        self.pushButton_4.clicked.connect(self.plainTextEdit_5.close) # type: ignore
        self.pushButton_9.clicked.connect(self.plainTextEdit_5.close) # type: ignore
        self.pushButton_5.clicked.connect(self.plainTextEdit_5.close) # type: ignore
        self.pushButton_6.clicked.connect(self.plainTextEdit_5.close) # type: ignore
        self.pushButton_7.clicked.connect(self.plainTextEdit_5.close) # type: ignore
        self.pushButton_13.clicked.connect(self.plainTextEdit_5.close) # type: ignore
        self.pushButton_10.clicked.connect(self.plainTextEdit_5.close) # type: ignore
        self.pushButton_14.clicked.connect(self.listView_6.show) # type: ignore
        self.pushButton_14.clicked.connect(self.plainTextEdit_5.show) # type: ignore
        self.pushButton_4.clicked.connect(self.plainTextEdit_6.close) # type: ignore
        self.pushButton_9.clicked.connect(self.plainTextEdit_6.close) # type: ignore
        self.pushButton_5.clicked.connect(self.plainTextEdit_6.close) # type: ignore
        self.pushButton_6.clicked.connect(self.plainTextEdit_6.close) # type: ignore
        self.pushButton_13.clicked.connect(self.plainTextEdit_6.close) # type: ignore
        self.pushButton_10.clicked.connect(self.plainTextEdit_6.close) # type: ignore
        self.pushButton_14.clicked.connect(self.plainTextEdit_6.close) # type: ignore
        self.pushButton_7.clicked.connect(self.plainTextEdit_6.show) # type: ignore
        self.pushButton_7.clicked.connect(self.pushButton_6.close) # type: ignore
        self.pushButton_9.clicked.connect(self.pushButton_6.close) # type: ignore
        self.pushButton_9.clicked.connect(self.pushButton_7.close) # type: ignore
        self.pushButton_9.clicked.connect(self.pushButton_13.close) # type: ignore
        self.pushButton_9.clicked.connect(self.pushButton_10.close) # type: ignore
        self.pushButton_9.clicked.connect(self.pushButton_14.close) # type: ignore
        self.pushButton_9.clicked.connect(self.listView.close) # type: ignore
        self.pushButton_9.clicked.connect(self.listWidget.show) # type: ignore
        self.pushButton_4.clicked.connect(self.listWidget.close) # type: ignore
        self.pushButton_5.clicked.connect(self.listWidget.close) # type: ignore
        self.pushButton_6.clicked.connect(self.listWidget.close) # type: ignore
        self.pushButton_7.clicked.connect(self.listWidget.close) # type: ignore
        self.pushButton_9.clicked.connect(self.textBrowser.show) # type: ignore
        self.pushButton_9.clicked.connect(self.textBrowser.show) # type: ignore
        self.pushButton_5.clicked.connect(self.textBrowser.close) # type: ignore
        self.pushButton_4.clicked.connect(self.textBrowser.close) # type: ignore
        self.pushButton_6.clicked.connect(self.textBrowser.close) # type: ignore
        self.pushButton_7.clicked.connect(self.textBrowser.close) # type: ignore
        self.pushButton_4.clicked.connect(self.textBrowser_2.show) # type: ignore
        self.pushButton_5.clicked.connect(self.textBrowser_2.close) # type: ignore
        self.pushButton_9.clicked.connect(self.textBrowser_2.close) # type: ignore
        self.pushButton_6.clicked.connect(self.textBrowser_2.close) # type: ignore
        self.pushButton_7.clicked.connect(self.textBrowser_2.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_5.setText(_translate("Dialog", "Menu page"))
        self.pushButton_4.setText(_translate("Dialog", "Main page"))
        self.pushButton_6.setText(_translate("Dialog", "คาเฟ่แมว"))
        self.pushButton_7.setText(_translate("Dialog", "ความเชื่อเกี่ยวกับแมว"))
        self.pushButton_9.setText(_translate("Dialog", "About us"))
        self.pushButton_10.setText(_translate("Dialog", "Caturday Cat Café"))
        self.pushButton_14.setText(_translate("Dialog", "Chico Design Bangkok"))
        self.plainTextEdit_3.setPlainText(_translate("Dialog", "สถานที่:\n"
"ซอย8 ถ.นราธิวาสราชนครินทร์\n"
"(สถานี BTS ที่ใกล้ที่สุด: สุรศักดิ์)\n"
"\n"
"เวลาเปิดทำการ:\n"
"จันทร์-อาทิตย์\n"
"11.00 - 20.00 น.\n"
"(หยุดทุกวันพุธ)\n"
"\n"
"ช่องทางติดต่อ:\n"
"โทร 089-665-6425"))
        self.pushButton_13.setText(_translate("Dialog", "CatNip Café"))
        self.plainTextEdit_4.setPlainText(_translate("Dialog", "สถานที่:\n"
"โครงการ Coco Walk ราชเทวี\n"
"(สถานี BTS ที่ใกล้ที่สุด: ราชเทวี)\n"
"\n"
"เวลาเปิดทำการ:\n"
"อังคาร-อาทิตย์\n"
"12.00 - 21.00 น.\n"
"(หยุดทุกวันจันทร์)\n"
"\n"
"ช่องทางติดต่อ:\n"
"โทร 02-656-5247\n"
""))
        self.plainTextEdit_5.setPlainText(_translate("Dialog", "สถานที่:\n"
"ซอย 53 ถนนสุขุมวิท\n"
"\n"
"เวลาเปิดทำการ:\n"
"09.30 - 18.00 น.\n"
"\n"
"ช่องทางติดต่อ:\n"
"โทร 02-258-6557"))
        self.plainTextEdit_6.setPlainText(_translate("Dialog", ">ความเชื่อของแต่ละประเทศ<\n"
"\n"
"-เนเธอร์แลน\n"
"แมวเป็นสัตว์ขี้เมาท์ ห้ามพูดความลับกับแมว\n"
"\n"
"-ญี่ปุ่น\n"
"ถ้าแมวล้างหน้าด้วยอุ้งเท้า จะมีคนมาหาและแมวกวักช่วยนำโชค\n"
"\n"
"-อินโดนีเซีย\n"
"ถ้าอยากให้ฝนตก เทน้ำใส่แมว\n"
"\n"
"-ไอซ์แลนด์\n"
"จะโดนแมวจับกินในวันคริสต์มาส\n"
"และถ้าไม่ใส่เสื้อผ้าใหม่ในวันคริสต์มาสอีฟ\n"
"\n"
"-อิตาลี\n"
"แมวจามมแปลว่าจะโชคดี\n"
"\n"
"-รัสเซีย\n"
"เลี้ยงแมว Russian Blue จะทำให้โชคดี"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">สมาชิก</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">นายปิยะ หลามสกุล 116310462023-7</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">น.ส.กวินธิดา สาขำ 116310400030-7</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#966496;\">HELLO CATS</span></p></body></html>"))
        
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
